export const PRODUCTS_NAME = [
  {
    gameId: 1,
    gameName: "Money Row",
    gameRoute: "/money-row/dashboard",
    gameIcon: "fas fa-money-bill",
    gameDescription: "*711*33#",
    gameShortcode: "*711*33#",
    gameRouteJoined: "money-row",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 2,
    gameName: "Lotto Bible",
    gameRouteJoined: "lotto-bible",
    gameRoute: "/lotto-bible/dashboard",
    gameIcon: "fas fa-book",
    gameDescription: "*713*2574#",
    gameShortcode: "*713*2574#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 3,
    gameName: "Lucky Buck",
    gameRoute: "/lucky-buck/dashboard",
    gameRouteJoined: "lucky-buck",
    gameIcon: "fas fa-coins",
    gameDescription: "*711*35#",
    gameShortcode: "*711*35#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 4,
    gameName: "Mr. Tips",
    gameRoute: "/mr-tips/dashboard",
    gameIcon: "fas fa-lightbulb",
    gameDescription: "*711*32#",
    gameShortcode: "*711*32#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 5,
    gameName: "Lotto Choice",
    gameRoute: "/lotto-choice/dashboard",
    gameIcon: "fas fa-check-square",
    gameDescription: "*713*2573#",
    gameShortcode: "*713*2573#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 6,
    gameName: "Big Money",
    gameRoute: "/big-money/dashboard",
    gameIcon: "fas fa-sack-dollar",
    gameDescription: "*713*2576#",
    gameShortcode: "*713*2576#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 7,
    gameName: "Hot Numbers",
    gameRoute: "/hot-numbers/dashboard",
    gameIcon: "fas fa-star",
    gameDescription: "*713*2575#",
    gameShortcode: "*713*2575#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 8,
    gameName: "Lotto Keys Plus",
    gameRoute: "/lotto-key-plus/dashboard",
    gameIcon: "fas fa-key",
    gameDescription: "*713*2272#",
    gameShortcode: "*713*2272#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 9,
    gameName: "Sure Banker",
    gameRoute: "/sure-banker/dashboard",
    gameIcon: "fas fa-shield-alt",
    gameDescription: "*711*31#",
    gameShortcode: "*711*31#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 10,
    gameName: "Lucky Picks Two Sure",
    gameRoute: "/lucky-picks-two-sure/dashboard",
    gameIcon: "fas fa-hand-peace",
    gameDescription: "*711*34#",
    gameShortcode: "*711*34#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 11,
    gameName: "VIP Super",
    gameRoute: "/vip-super/dashboard",
    gameIcon: "fas fa-crown",
    gameDescription: "*713*2571#",
    gameShortcode: "*713*2571#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 12,
    gameName: "Lotto Guide",
    gameRoute: "/lotto-guide/dashboard",
    gameIcon: "fas fa-map-signs",
    gameDescription: "*713*2572#",
    gameShortcode: "*713*2572#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
  {
    gameId: 13,
    gameName: "Lotto Star",
    gameRoute: "/lotto-star/dashboard",
    gameRouteJoined: "lotto-star",
    gameIcon: "fas fa-star",
    gameDescription: "*711*34#",
    gameShortcode: "*711*34#",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.jpg",
  },
];
