export const PRODUCTS_NAME = [
  {
    gameId: 1,
    gameName: "Sports Lord",
    gameRoute: "/money-row/dashboard",
    gameIcon: "fas fa-money-bill",
    gameDescription: "*",
    gameShortcode: "*",
    gameRouteJoined: "money-row",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  },
  {
    gameId: 2,
    gameName: "Sports Lord",
    gameRoute: "/money-row/dashboard",
    gameIcon: "fas fa-money-bill",
    gameDescription: "*",
    gameShortcode: "*",
    gameRouteJoined: "money-row",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  },
  {
    gameId: 3,
    gameName: "Sports Lord",
    gameRoute: "/money-row/dashboard",
    gameIcon: "fas fa-money-bill",
    gameDescription: "*",
    gameShortcode: "*",
    gameRouteJoined: "money-row",
    tag: "Active",
    gameImage: "../assets/images/games-icons/app.png",
  }
];
