export enum SERVICE_TYPES {
  BusinessKey = 'BUSINESS_KEY',
  Heartwise = 'HEARTWISE',
  LoveRelationships = 'LOVE_TIPS',
  JobAlerts = 'JOB_ALERTS',
  JobConnect = 'JOB_CONNECT',
  Finance = 'FINANCE_PRO',
  Motivation = 'MOTIVATION',
  Scholarships = 'SCHOLARSHIPS',
  BetLord = 'BET_LORD',
  Flashscore = 'FLASHSCORE',
  TopMatches = 'TOP_MATCHES',
  HuskyOdds = 'HUSKY_ODDS',
  Sportaga = 'SPORTAGA',
  OddsOracle = 'ODDS_ORACLE',
  KingSolomon = 'KING_SOLOMON',
  SuccessTips = 'SUCCESS_TIPS',
  FinancePro = 'FINANCE_PRO',
  Cashflow = 'CASHFLOW',
}

export const serviceTypeOptions = [
  { key: 'business_key', value: SERVICE_TYPES.BusinessKey },
  { key: 'heartwise', value: SERVICE_TYPES.Heartwise },
  { key: 'love_relationships', value: SERVICE_TYPES.LoveRelationships },
  { key: 'job_alerts', value: SERVICE_TYPES.JobAlerts },
  { key: 'job_connect', value: SERVICE_TYPES.JobConnect },
  { key: 'finance', value: SERVICE_TYPES.Finance },
  { key: 'motivation', value: SERVICE_TYPES.Motivation },
  { key: 'scholarships', value: SERVICE_TYPES.Scholarships },
  { key: 'bet_lord', value: SERVICE_TYPES.BetLord },
  { key: 'flashscore', value: SERVICE_TYPES.Flashscore },
  { key: 'top_matches', value: SERVICE_TYPES.TopMatches },
  { key: 'husky_odds', value: SERVICE_TYPES.HuskyOdds },
  { key: 'sportaga', value: SERVICE_TYPES.Sportaga },
  { key: 'odds_oracle', value: SERVICE_TYPES.OddsOracle },
  { key: 'king_solomon', value: SERVICE_TYPES.KingSolomon },
  { key: 'success_tips', value: SERVICE_TYPES.SuccessTips },
  { key: 'cashflow', value: SERVICE_TYPES.Cashflow },
];